---

- name: Get index contents
  uri:
    url: http://{{ ansible_ssh_host }}:9000/
    status_code: 200
    return_content: yes
  register: response_check

- debug:
    msg: "{{ response_check.content }}"
